/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacadastro.alugarveiculo;

import alugar.Alugar;
import conexao.alugardao.AlugarDao;
import conexao.pessoadao.ClienteDao;
import conexao.veiculodao.VeiculoDao;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pessoamodel.Cliente;
import veiculomodel.Veiculo;

/**
 *
 * @author Novo Usuario
 */
public class AlugarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form AlugarVeiculo
     */
    public AlugarVeiculo() {
        initComponents();
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoPlaca = new javax.swing.JTextField();
        btnBuscarVeiculo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnListaVeiculosDisponiveis = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoDataInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoDataFim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        exemploCpf = new javax.swing.JLabel();
        exemploData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cpf:");

        campoCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCpfFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Placa do Veiculo:");

        btnBuscarVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarVeiculo.setText("BUSCAR");
        btnBuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVeiculoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("ALUGAR VEÍCULO");

        btnListaVeiculosDisponiveis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaVeiculosDisponiveis.setText("CLIQUE AQUI");
        btnListaVeiculosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVeiculosDisponiveisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Conferir lista de Veículos disponíveis");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Data de Inicio:");

        campoDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataInicioFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Data Final:");

        campoDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataFimFocusLost(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("*Preencha todos os campos corretamente");

        exemploCpf.setText("Ex: 123.456.789-10");

        exemploData.setText("Ex: 01/01/2023");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(btnListaVeiculosDisponiveis))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exemploData))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(106, 106, 106)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exemploCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(campoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarVeiculo))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnListaVeiculosDisponiveis)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exemploCpf)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exemploData)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(campoDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarVeiculo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaVeiculosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVeiculosDisponiveisActionPerformed
        // TODO add your handling code here:
        VeiculoDao.veiculoDisponiveis();
    }//GEN-LAST:event_btnListaVeiculosDisponiveisActionPerformed

    private void btnBuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVeiculoActionPerformed
        // TODO add your handling code here:
        try 
        {   
            //se retornar ok nao pede pra preencher os campos 
            if ((verificaCpf())&&(verificaPlaca())&&verificaData()) 
            {
                 
                 if((ClienteDao.isClienteCadastrado(campoCpf.getText()))&&(VeiculoDao.isVeiculoDisponivel(campoPlaca.getText())))
                {
                    Cliente cliente = ClienteDao.clienteCadastrado(campoCpf.getText());
                    Veiculo veiculo = VeiculoDao.veiculoDisponivel(campoPlaca.getText());
                    Alugar alugar = new Alugar(cliente, veiculo,campoDataInicio.getText(),campoDataFim.getText());
                    AlugarDao.registroAluguel(alugar);
                    VeiculoDao.setVeiculoIndisponivel(veiculo.getIdVeiculo());
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado", "Sucesso ao Cadastrar Locação", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Não foi possivel prosseguir tente novamente", "ERRO", JOptionPane.INFORMATION_MESSAGE);
                }  
            } 
            else
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar o aluguel no sistema, Exception: "+ e, "ERRO NO CADASTRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscarVeiculoActionPerformed

    private void campoCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFocusGained
        // TODO add your handling code here:
        if(campoCpf.getText().isEmpty())
        {
            exemploCpf.setVisible(true);
        }
        
    }//GEN-LAST:event_campoCpfFocusGained

    private void campoCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFocusLost
        // TODO add your handling code here:
        if(!campoCpf.getText().isEmpty())
        {
            exemploCpf.setVisible(false);
        }
    }//GEN-LAST:event_campoCpfFocusLost

    private void campoDataInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataInicioFocusGained
        // TODO add your handling code here:
        if(campoDataInicio.getText().isEmpty())
        {
             exemploData.setVisible(true);
        }
    }//GEN-LAST:event_campoDataInicioFocusGained

    private void campoDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataInicioFocusLost
        // TODO add your handling code here:
        if(!campoDataInicio.getText().isEmpty())
        {
            exemploData.setVisible(false);
        }
    }//GEN-LAST:event_campoDataInicioFocusLost

    private void campoDataFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFimFocusGained
        // TODO add your handling code here:
       /* if(campoDataFim.getText().equals("03/01/2023"))
        {
            campoDataFim.setText("");
        }*/
    }//GEN-LAST:event_campoDataFimFocusGained

    private void campoDataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataFimFocusLost
        // TODO add your handling code here:
        /*if(campoDataFim.getText().isEmpty())
        {
            campoDataFim.setText("03/01/20223");
        }*/
    }//GEN-LAST:event_campoDataFimFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlugarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarVeiculo().setVisible(true);
            }
        });
    }
    private boolean verificaCpf()
    {
        //se o campo não estiver vazio
        if(!(campoCpf.getText().trim().isEmpty()))
        { 
            String cpf = campoCpf.getText();
            try
            {
                Cliente cliente = new Cliente();
                //verifica se apenas numeros foram inseridos
                cpf = cpf.replaceAll("[^0-9]", "");
                Long.parseLong(cpf);
                campoCpf.setText(cliente.formatarCpf(cpf));
                return true;    
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Insira apenas números, Exception: "+ e, "Cpf", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        else
        {
            return false;
        }
    }
    private boolean verificaPlaca()
    {
        if(!campoPlaca.getText().trim().isEmpty())
        {
            try
            {
                String placa = campoPlaca.getText();
                Veiculo veiculo = new Veiculo();
                placa = veiculo.formatarPlaca(placa);
                campoPlaca.setText(placa);
                return true;
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Não foi possivel verificar placa, Exception: "+ e, "Verifica Placa", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        else
        {
            return false;
        }
    }
    private boolean verificaData()
    {
        if((campoDataInicio.getText().trim().isEmpty()) || (campoDataFim.getText().trim().isEmpty()))
        {
            return false;
        }
        else
        {
            
            try
            {
               Alugar alugar = new Alugar();
               String dataInicio = alugar.formatarData(campoDataInicio.getText());
               campoDataInicio.setText(dataInicio);
               String dataFim = alugar.formatarData(campoDataFim.getText());
               campoDataFim.setText(dataFim);
               return true;
            }
            catch (Exception e)
            {
                // Se ocorrer uma exceção ao fazer parsing, a data é inválida ou está no formato incorreto
                JOptionPane.showMessageDialog(null, "Formato da data está inválido, Exception: "+ e, "Erro Data", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVeiculo;
    private javax.swing.JButton btnListaVeiculosDisponiveis;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoDataFim;
    private javax.swing.JTextField campoDataInicio;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JLabel exemploCpf;
    private javax.swing.JLabel exemploData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
