/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telacadastro.telaalugueisativos;

import alugar.Alugar;
import conexao.alugardao.AlugarDao;
import conexao.veiculodao.VeiculoDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Novo Usuario
 */
public class AlugueisAtivos extends javax.swing.JFrame {

    /**
     * Creates new form AlugueisAtivos
     */
    public AlugueisAtivos() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnListaAlugueis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNCadastro = new javax.swing.JTextField();
        btnFinalizarContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Alugueis Ativos: ");

        btnListaAlugueis.setText("Verificar");
        btnListaAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAlugueisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Finalizar Contrato");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Alugueis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Insira o Número do cadastro: ");

        btnFinalizarContrato.setText("Finalizar");
        btnFinalizarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(btnListaAlugueis))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnFinalizarContrato)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnListaAlugueis))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addComponent(btnFinalizarContrato)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarContratoActionPerformed
        // TODO add your handling code here:
       
        if(this.verificaNCadastro())
        {
            try
            {
                String resp = JOptionPane.showInputDialog("Deseja realmente encerrar o contrato? [Sim/Não]","Confirmar ação");
                if(resp.toUpperCase().equals("SIM"))
                {
                    try
                    {
                        Alugar alugar;
                        alugar = AlugarDao.getAlugado(Integer.parseInt(campoNCadastro.getText()));
                        if(alugar!=null)
                        {
                             AlugarDao.encerrarAluguel(alugar.getId());
                             VeiculoDao.setVeiculoDisponivel(alugar.getIdVeiculo());
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Registro Não encontrado");
                        }
                    }
                    catch(NullPointerException e)
                    {
                         JOptionPane.showMessageDialog(null,"Erro ao cancelar Locação, Exception: "+e, "Erro na Busca", JOptionPane.ERROR_MESSAGE);
                    }
                      
                }
                else if(resp.toUpperCase().equals("NÃO"))
                {
                    JOptionPane.showMessageDialog(null,"Operação cancelada pelo usuário.");
                    campoNCadastro.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Insira sim ou não, voltando ao menu anterior.");
                    campoNCadastro.setText("");
                }
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Insira Sim ou Não, exceção: "+e, "Entrada inválida", JOptionPane.ERROR_MESSAGE);
            }
        }
       
       
    }//GEN-LAST:event_btnFinalizarContratoActionPerformed
    private boolean verificaNCadastro()
    {
        if(!campoNCadastro.getText().isEmpty())
        {
            try
            {
                String numeroCadastro = campoNCadastro.getText();
                Long nCadastro = Long.parseLong(numeroCadastro);
                campoNCadastro.setText(numeroCadastro);
                return true;
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Insira um número, exceção: "+e, "Entrada inválida", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "O campo não pode está vazio");
            return false;
        }
    }
    private void btnListaAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAlugueisActionPerformed
        // TODO add your handling code here:
        AlugarDao.listaAlugueis();
    }//GEN-LAST:event_btnListaAlugueisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlugueisAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlugueisAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlugueisAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlugueisAtivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugueisAtivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarContrato;
    private javax.swing.JButton btnListaAlugueis;
    private javax.swing.JTextField campoNCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
